version: '3.8'

services:
  backend:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017/teste_shopper_db
    depends_on:
      - mongo
    # Comando de entrada para o ambiente de produção
    command: ['node', 'dist/server.js']

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: teste_shopper_db

volumes:
  mongo-data:
