version: '3.8'

services:
  backend:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/teste_shopper_db
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    entrypoint: ['sh', '-c', './create-env.sh && npm run dev']
  # Serviço para o MongoDB
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: teste_shopper_db

# Volumes para persistir os dados do MongoDB
volumes:
  mongo-data:
